// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCai7coWSW1dvomaStzJNUZf6_zv0nbBrI',
    appId: '1:1042423029466:web:61ecf4c6fe3aebe9f9cfe3',
    messagingSenderId: '1042423029466',
    projectId: 'koylafirebasetest',
    authDomain: 'koylafirebasetest.firebaseapp.com',
    storageBucket: 'koylafirebasetest.appspot.com',
    measurementId: 'G-JR7S64HY59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5QLY_DMs_0gxuCEd-efLGoG1GIr76k2c',
    appId: '1:1042423029466:android:5d2769a5eae12d21f9cfe3',
    messagingSenderId: '1042423029466',
    projectId: 'koylafirebasetest',
    storageBucket: 'koylafirebasetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaeOZcWFPnqH9rmkZ67myNzp4nzCu_Lek',
    appId: '1:1042423029466:ios:6b56c852fa5f2d99f9cfe3',
    messagingSenderId: '1042423029466',
    projectId: 'koylafirebasetest',
    storageBucket: 'koylafirebasetest.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaeOZcWFPnqH9rmkZ67myNzp4nzCu_Lek',
    appId: '1:1042423029466:ios:6b56c852fa5f2d99f9cfe3',
    messagingSenderId: '1042423029466',
    projectId: 'koylafirebasetest',
    storageBucket: 'koylafirebasetest.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCai7coWSW1dvomaStzJNUZf6_zv0nbBrI',
    appId: '1:1042423029466:web:e405287ec57058bff9cfe3',
    messagingSenderId: '1042423029466',
    projectId: 'koylafirebasetest',
    authDomain: 'koylafirebasetest.firebaseapp.com',
    storageBucket: 'koylafirebasetest.appspot.com',
    measurementId: 'G-3EBCLPDMNW',
  );
}
